### ISSUE TITLE
Email sent but empty

### ISSUE THREAD

**Issue by Angahuan** [splitbrain/dokuwiki-plugin-bureaucracy#184]
Using "action mail" the email is successfully sent and received but without the data from the from.
The "subject" and "thanks" are working properly.

**Comment by harkx** [comment]
Works here, you might want to show how you created it?
And ... is sendmail working from your linux cli ?

**Comment by ehefley** [comment]
I'm experiencing this issue as well. Any resolution?

**Comment by ehefley** [comment]
It's been a while but I a circling back around to this. I am using the SMTP plugin and trying to send data from a from via email. The email sends just fine but it is blank.

**Comment by harkx** [comment]
Works here, you might want to show how you created it?
**And** ... is sendmail working from your linux cli ?

**Comment by dmdewey** [comment]
I've got the same issue with a DokuWiki installed on an intranet server. There's a Drupal site on the server as well that does not have any issues with sending mail using SMTP. I'm going to dig through the logs to try to find the issue and post back here.

**Comment by vb-git** [comment]
Only thing i have to add is that i experienced the same problem and have found a "workaround":
I moved dokuwiki to a new server and because of newer PHP i switched from swiftmailer plugin to smtp plugin. This caused the empty email problem. I then reverted back to swiftmailer and everything started working again.

**Comment by dmdewey** [comment]
I had to abandon the issue for now but will definitely revisit later. I did suspect our Barracuda Email firewall was to blame but that would not make sense if Drupal was sending emails just fine after being configured via smtp. I’m going to see how IIS supports various PHP applications and circle back around to this issue.

**Comment by dmgahoehe** [comment]
Hi folks,
same problem here. Built a new Server with latest xampp (PHP7), copied Dokuwiki to it. Then updated DW to "Release 2018-04-22 'Greebo'". After that I experienced problems with "Switftmailer" (had to replace '=&'  by '=') but still had problems with multiple files when trying to send email. So I installed 'SMTP Plugin' instead.
Sending Mails works technically fine (test connection from admin menu, changing password, editing a page). But all Mails are without content. Only the correct headers appear.
I cannot revert to Swiftmailer because of the errors (which I copied to the end of this post).

I would appreciate if the Swiftmailer-Plugin was made compatible to PHP7 or even better if the SMTP-Plugin would send mails with a content.

---------------- 
`
Fatal error: Uncaught Error: Call to undefined function split() in C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\Swift.php:277 Stack trace: #0 C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\Swift.php(261): Swift->setConnectionExtensions(Array) #1 C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\Swift.php(220): Swift->handshake(Object(Swift_Events_ResponseEvent)) #2 C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\Swift.php(101): Swift->connect() #3 C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\action.php(61): Swift->__construct(Object(Swift_Connection_SMTP), 'appserver.local....') #4 C:\xampp\htdocs\dokuwiki-it\inc\events.php(229): action_plugin_swiftmail->handle_message_send(Object(Doku_Event), Array) #5 C:\xampp\htdocs\dokuwiki-it\inc\events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE') #6 C:\xampp\htdocs\dokuwiki-it\inc\Mailer.class.php(682): Doku_Event->advise_before(true) #7 C:\xampp\htdocs\dokuwiki-it\inc\subscription.php(617): Mailer->send() #8 C:\xampp\htdocs\dokuwiki-it\inc\ in C:\xampp\htdocs\dokuwiki-it\lib\plugins\swiftmail\Swift.php on line 277
`
